export const ROUTES = {
    HOME_ROUTE: '/',
    LOGIN_ROUTE: '/login',
    USERS_ROUTE: '/users',
    ORDERS_ROUTE: '/orders',
    SALES_ANALYSIS_ROUTE: '/sales-analysis',
    RATES_ROUTE: '/rates',
    REPORTS_ROUTE: '/reports',
    NOT_FOUND_ROUTE: '/not-found',
    PROFILE_ROUTE: '/profile',
    SETTINGS_ROUTE: '/settings',
    ABOUT_ROUTE: '/about',
    CONTACT_ROUTE: '/contact',
    HELP_ROUTE: '/help',
    ARTIST_PROFILE_ROUTE: 'profile/artist',
    CLIENT_PROFILE_ROUTE: 'profile/client',
    SEND_MESSAGE_ROUTE: '/send-message',
    CLIENT_ORDERS_ROUTE: 'orders',
    CLIENT_RATES_ROUTE: 'rates',
    CLIENT_ACTIVITY_LOG_ROUTE: 'activity-log',
}